### ISSUE TITLE
How much of Arc does Clamp implement?

### ISSUE THREAD

**Issue by alexispurslane** [arclanguage/Clamp#1]
I was recently searching for a Lisp that would fit my needs better than Racket (Racket is too verbose, slow, and academic). Common Lisp looked great and Arc looked even better, and I feel like this combination of the two would be perfect, especially since I could then use SLIME with my Emacs setup. However, I wanted to go through the http://arclanguage.github.io/ref/ tutorial, and wanted to know: how much of that will work with Clamp? What features are missing, etc.?

**Comment by akkartik** [comment]
I'm not an expert but I imagine the coverage would be pretty good! Try the tut and tell us if you spot something amiss.

**Comment by alexispurslane** [comment]
I will. If this project ever dies, I'd be willing to at least shoulder part of the maintenance, FYI. I've decided to make this my main Lisp.
